name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
  
    steps:
    - uses: actions/checkout@v3
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1.0.13
    - name: build
      run: xmake -b
