on:
  push:
    branches:
    - redo
  pull_request:
    branches:
    - redo

jobs:
  my_job:
    name: Lint the source files
    runs-on: ubuntu-latest

    steps:
    - name: Linting
      uses: cpp-linter/cpp-linter-action@v2.6.1
